export const Env = {
  NEXTGA_TRACKING: process.env.NEXT_PUBLIC_GA_TRACKING,

  HYGRAPH_API_URL: process.env.NEXT_PUBLIC_HYGRAPH_API_URL,
  HYGRAPH_TOKEN: process.env.NEXT_PUBLIC_HYGRAPH_TOKEN,

  INSTAGRAM_API_MEDIA_URL: process.env.NEXT_PUBLIC_INSTAGRAM_API_MEDIA_URL,
  INSTAGRAM_TESTER_TOKEN: process.env.NEXT_PUBLIC_INSTAGRAM_TESTER_TOKEN,
};
